apiVersion: v1
kind: Secret
metadata:
  name: chat-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MTIzMzIxNDU=
  POSTGRES_DB: Y2hhdA==
  POSTGRES_HOST: cG9zdGdyZXMuaGVhbHRoLW1hbmFnZW1lbnQuc3ZjLmNsdXN0ZXIubG9jYWw=